# Generated by Django 5.1.15 on 2025-12-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_berita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='tanggal',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='penulis',
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
