# Generated by Django 5.1.15 on 2025-12-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_tanggal_berita_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-created_at']},
        ),
    ]
