# Generated by Django 5.1.15 on 2025-12-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_berita_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
